import Foundation

// MARK: - Built-in content

enum Content {
    static let quotes: [(String, String)] = [
        // Stoics
        ("What stands in the way becomes the way.", "Marcus Aurelius"),
        ("Waste no more time arguing what a good man should be. Be one.", "Marcus Aurelius"),
        ("Confine yourself to the present.", "Marcus Aurelius"),
        ("We suffer more often in imagination than in reality.", "Seneca"),
        ("While we are postponing, life speeds by.", "Seneca"),
        ("Difficulties strengthen the mind, as labor does the body.", "Seneca"),
        ("It is not that we have a short time to live, but that we waste a lot of it.", "Seneca"),
        ("If a man knows not to which port he sails, no wind is favorable.", "Seneca"),
        ("No man was ever wise by chance.", "Seneca"),
        ("Begin at once to live.", "Seneca"),
        ("No man is free who is not master of himself.", "Epictetus"),
        ("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant"),
        ("Knowing is not enough; we must apply.", "Johann Wolfgang von Goethe"),

        // Builders
        ("Move fast and break things.", "Mark Zuckerberg"),
        ("Done is better than perfect.", "Facebook office poster"),
        ("If you are not embarrassed by the first version of your product, you've launched too late.", "Reid Hoffman"),
        ("Only the paranoid survive.", "Andy Grove"),
        ("Bad companies are destroyed by crises. Good companies survive them. Great companies are improved by them.", "Andy Grove"),
        ("Competition is for losers.", "Peter Thiel"),
        ("What important truth do very few people agree with you on?", "Peter Thiel"),
        ("Make something people want.", "Paul Graham"),
        ("Do things that don't scale.", "Paul Graham"),
        ("Live in the future, then build what's missing.", "Paul Graham"),
        ("We are stubborn on vision. We are flexible on details.", "Jeff Bezos"),
        ("Software is eating the world.", "Marc Andreessen"),
        ("There are no silver bullets for this, only lead bullets.", "Ben Horowitz"),
        ("Play long-term games with long-term people.", "Naval Ravikant"),
        ("It's not about ideas. It's about making ideas happen.", "Scott Belsky"),
        ("There is nothing so useless as doing efficiently that which should not be done at all.", "Peter Drucker"),
        ("Plans are worthless, but planning is everything.", "Dwight D. Eisenhower"),
        ("If everything seems under control, you're not going fast enough.", "Mario Andretti"),
        ("Don't be afraid to give up the good to go for the great.", "John D. Rockefeller"),
        ("If it doesn't sell, it isn't creative.", "David Ogilvy"),

        // Discipline
        ("Everybody has a plan until they get punched in the mouth.", "Mike Tyson"),
        ("Discipline is doing what you hate to do, but doing it like you love it.", "Mike Tyson"),
        ("Discipline equals freedom.", "Jocko Willink"),
        ("Leaders must own everything in their world. There is no one else to blame.", "Jocko Willink"),
        ("I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", "Bruce Lee"),
        ("Absorb what is useful, discard what is useless, and add what is specifically your own.", "Bruce Lee"),
        ("Gold medals aren't really made of gold. They're made of sweat, determination, and a hard-to-find alloy called guts.", "Dan Gable"),
        ("Once you've wrestled, everything else in life is easy.", "Dan Gable"),
        ("Don't quit. Suffer now and live the rest of your life as a champion.", "Muhammad Ali"),
        ("Rest at the end, not in the middle.", "Kobe Bryant"),
        ("I've failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan"),
        ("The score takes care of itself.", "Bill Walsh"),
        ("Victorious warriors win first and then go to war.", "Sun Tzu"),
        ("Slow is smooth, smooth is fast.", "Military saying"),
        ("Talent is cheaper than table salt. What separates the talented from the successful is a lot of hard work.", "Stephen King"),

        // Writing
        ("If it sounds like writing, I rewrite it.", "Elmore Leonard"),
        ("Try to leave out the part that readers tend to skip.", "Elmore Leonard"),
        ("Writing is thinking on paper.", "William Zinsser"),
        ("Clear thinking becomes clear writing; one can't exist without the other.", "William Zinsser"),
        ("Clutter is the disease of American writing.", "William Zinsser"),
        ("You can't wait for inspiration. You have to go after it with a club.", "Jack London"),
        ("Almost all good writing begins with terrible first efforts.", "Anne Lamott"),
        ("Perfectionism is the voice of the oppressor.", "Anne Lamott"),
        ("Start as close to the end as possible.", "Kurt Vonnegut"),
        ("Every sentence must do one of two things: reveal character or advance the action.", "Kurt Vonnegut"),
        ("Omit needless words.", "William Strunk Jr."),
        ("I have made this longer than usual because I have not had time to make it shorter.", "Blaise Pascal"),
        ("It is only by going through a volume of work that you will close that gap.", "Ira Glass"),
        ("Be regular and orderly in your life, so that you may be violent and original in your work.", "Gustave Flaubert"),
        // Art and photography
        ("Your first 10,000 photographs are your worst.", "Henri Cartier-Bresson"),
        ("If your pictures aren't good enough, you're not close enough.", "Robert Capa"),
        ("You don't take a photograph, you make it.", "Ansel Adams"),
        ("Twelve significant photographs in any one year is a good crop.", "Ansel Adams"),
        ("f/8 and be there.", "Weegee"),
        ("The camera is an instrument that teaches people how to see without a camera.", "Dorothea Lange"),
        ("Which of my photographs is my favorite? The one I'm going to take tomorrow.", "Imogen Cunningham"),
        ("All photographs are accurate. None of them is the truth.", "Richard Avedon"),
        ("I photograph to find out what something will look like photographed.", "Garry Winogrand"),
        ("A photograph is a secret about a secret. The more it tells you the less you know.", "Diane Arbus"),
        ("It is more important to click with people than to click the shutter.", "Alfred Eisenstaedt"),
        ("Don't think about making art, just get it done. Let everyone else decide if it's good or bad.", "Andy Warhol"),
        ("Making money is art and working is art and good business is the best art.", "Andy Warhol"),
        ("Less, but better.", "Dieter Rams"),
        ("Good design is as little design as possible.", "Dieter Rams"),
        ("If it can be written, or thought, it can be filmed.", "Stanley Kubrick"),
    ]

    static let facts: [String] = [
        "Honey found in ancient Egyptian tombs was still edible thousands of years later.",
        "A day on Venus is longer than its year.",
        "Botanically, bananas are berries and strawberries are not.",
        "Wombats produce cube-shaped poop.",
        "The Eiffel Tower grows about 15 cm taller in summer as its iron expands.",
        "Oxford University was already teaching students before the Aztec capital Tenochtitlan was founded.",
        "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
        "Sharks have existed longer than trees.",
        "A group of flamingos is called a flamboyance.",
        "Scotland's national animal is the unicorn.",
        "The designer of the Pringles can had some of his ashes buried in one.",
        "There are more possible games of chess than atoms in the observable universe.",
        "A lightning bolt is roughly five times hotter than the surface of the Sun.",
        "A typical cumulus cloud weighs about a million pounds.",
        "Nintendo was founded in 1889 as a playing card company.",
        "The dot over a lowercase i or j is called a tittle.",
        "The word \"robot\" comes from the Czech \"robota,\" meaning forced labor, via a 1920 play.",
        "Saturn is less dense than water. In a big enough bathtub, it would float.",
        "Sunlight takes about 8 minutes and 20 seconds to reach Earth.",
        "The Great Wall of China is not visible from the Moon with the naked eye.",
        "In 1947, engineers found an actual moth in the Harvard Mark II and logged it as the \"first actual case of bug being found.\"",
        "Bubble wrap was originally invented as textured wallpaper.",
        "The Moon drifts about 3.8 cm farther from Earth every year.",
        "\"Deadline\" first meant a boundary line at a Civil War prison camp that prisoners could not cross.",
        "In newsrooms, a slug is the short working name given to a story as it moves through editing.",
        "The first full Oxford English Dictionary was finished in 1928, about 70 years after it was proposed.",
        "Earth is the only planet in our solar system not named after a god.",
        "Pluto has not completed a single orbit of the Sun since it was discovered in 1930.",
        "The first photograph, taken by Nicéphore Niépce in the 1820s, needed an exposure of at least eight hours.",
        "There are more trees on Earth than stars in the Milky Way.",
        "Peanuts aren't nuts. They're legumes, like peas and lentils.",
        "Tim Berners-Lee published the first website in 1991.",
        "Alaska is the northernmost, westernmost, and easternmost U.S. state.",
        "France spans more time zones than any other country, thanks to its overseas territories.",
        "Canada has more lakes than the rest of the world combined.",
        "The first digital camera was built at Kodak in 1975. It captured 0.01 megapixels and took 23 seconds to save each image to cassette tape.",
        "The first color photograph, a tartan ribbon, was made in 1861 using a method proposed by physicist James Clerk Maxwell.",
        "Kodak's first camera, in 1888, came with the slogan \"You press the button, we do the rest.\"",
        "The first photo of a person was an accident: a man getting his boots shined stood still long enough to show up in Daguerre's 1838 street scene.",
        "Robert Cornelius took what may be the first selfie in 1839, sitting still for several minutes outside his family's shop.",
        "The word \"pixel\" is short for \"picture element.\"",
        "Ultramarine blue was ground from lapis lazuli and at times cost more than gold.",
        "\"Mummy brown\" was a real paint pigment made partly from ground-up Egyptian mummies.",
        "The Mona Lisa was stolen from the Louvre in 1911 and missing for more than two years.",
        "Leonardo da Vinci filled his notebooks with mirror writing, running right to left.",
        "Edvard Munch made several versions of The Scream, in paint, pastel, and print.",
        "Hubble's first images were blurry because its main mirror was ground wrong by about 2 micrometers, a fraction of a hair's width.",
        "The Blue Marble photo of the whole Earth was taken by the Apollo 17 crew in 1972.",
        "Apollo astronauts left about a dozen Hasselblad camera bodies on the Moon to save weight for rock samples.",
        "Instagram's first photo, posted by co-founder Kevin Systrom in 2010, was of a dog near a taco stand.",
        "Woolly mammoths were still alive when the Great Pyramid of Giza was built.",
        "Tyrannosaurus rex lived closer in time to us than to Stegosaurus.",
        "Harvard was founded before calculus was invented.",
        "The fax machine was patented in 1843, more than 30 years before the telephone.",
        "The lighter was invented a few years before the friction match.",
        "Betty White was born before sliced bread was sold.",
        "France's last execution by guillotine was in 1977, the year Star Wars came out.",
        "Neptune finished its first full orbit since its discovery in 2011, 165 years after astronomers found it.",
        "\"OK\" started as a joke abbreviation for \"oll korrect\" in an 1839 Boston newspaper.",
        "\"Upper case\" and \"lower case\" come from the separate cases printers kept their metal letters in.",
        "\"Cliché\" and \"stereotype\" were both printing terms for metal plates used to print the same thing again and again.",
        "\"Broadcast\" originally meant scattering seed by hand across a field.",
        "\"Clue\" comes from \"clew,\" a ball of thread, like the one Theseus used to escape the labyrinth.",
        "\"Nice\" originally meant foolish or ignorant.",
        "\"Muscle\" comes from the Latin for \"little mouse.\"",
        "The word \"serendipity\" was coined by Horace Walpole in 1754.",
        "The earliest known use of the word \"nerd\" is in Dr. Seuss's 1950 book If I Ran the Zoo.",
        "Calling junk messages \"spam\" comes from a Monty Python sketch.",
        "Play-Doh was first sold as a wallpaper cleaner.",
        "Post-it Notes came out of a failed attempt to make a super-strong glue.",
        "The microwave oven was discovered when a radar engineer noticed a candy bar melting in his pocket.",
    ]
}
